[project]
name = "hello"
version = "0.1.0"
description = "An example Django app running in Docker."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "django==6.0.2",
  "celery==5.6.2",
  "django-debug-toolbar==6.2.0",
  "gunicorn==25.0.1",
  "psycopg==3.3.2",
  "redis==7.1.0",
  "ruff==0.15.0",
  "setuptools==80.10.2",
  "whitenoise==6.11.0",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["I", "SIM"]
